export default function DataPage() {
    return null;
};

export const settings = {
    className: "center",
    centerPadding: "60px",
    dots: true,
    infinite: true,
    speed: 500,
    slidesToShow: 1,
    swipeToSlide: true,
    arrows: false,
    autoplay: true,
    autoplaySpeed: 2500,
    responsive: [
        {
            breakpoint: 1200,
            settings: {
                slidesToShow: 1,
                swipeToSlide: true,
                infinite: true,
                arrows: false,
                dots: true,
                autoplay: true,
                autoplaySpeed: 2000,
            },
        },
        {
            breakpoint: 991,
            settings: {
                slidesToShow: 1,
                swipeToSlide: true,
                infinite: true,
                arrows: false,
                dots: true,
                autoplay: true,
                autoplaySpeed: 2000,
            },
        },
        {
            breakpoint: 767,
            settings: {
                slidesToShow: 1,
                swipeToSlide: true,
                infinite: true,
                arrows: false,
                dots: true,
                autoplay: true,
                autoplaySpeed: 2000,
            },
        },
    ],
};
export const education = [
    {
        degree: "MCA",
        description: "<p>Galgotias University, Greater Noida<br />Specialization Subject: Software Development<br/>First Class with Distinction (9.07 CGPA)</p>",
        timePeriod: "2019-22",
        certificate: "/certificates/degree/MCA_Degree.pdf",
    },
    {
        degree: "B.Com",
        description: "<p>Delhi University<br />Specialization Subject: Computer Applications</p>",
        timePeriod: "2015-18",
        certificate: "",
    },
    {
        degree: "High School (10+2)",
        description: "<p>Universal Public School, Preet Vihar, Delhi-110092<br />Subject: Commerce with Maths</p>",
        timePeriod: "2014-15",
        certificate: "",
    },
];
export const certification = [
    {
        degree: "Information Security",
        description: "<p>HCLTech<br />Certificate of Completion</p>",
        timePeriod: "2025",
        certificate: "/certificates/certifications/Certificate_of_Completion_Information_Security.pdf",
    },
    {
        degree: "Export Compliance",
        description: "<p>HCLTech<br />Certificate of Completion</p>",
        timePeriod: "2025",
        certificate: "/certificates/certifications/Certificate_of_Completion_Export_Compliance.pdf",
    },
    {
        degree: "Dimensions of Data Privacy",
        description: "<p>HCLTech<br />Certificate of Completion</p>",
        timePeriod: "2025",
        certificate: "/certificates/certifications/Certificate_of_Completion_Dimensions_of_Data_Privacy.pdf",
    },
    // {
    //   degree: "Aptitude Rounds",
    //   description: "<p>Coding Ninjas<br />Certificate of Excellence</p>",
    //   timePeriod: "2024",
    //   certificate: "/certificates/certifications/Bootcamp-Aptitude_Rounds-Excellence.pdf",
    // },
    // {
    //   degree: "Operating Systems",
    //   description: "<p>Coding Ninjas<br />Certificate of Excellence</p>",
    //   timePeriod: "2024",
    //   certificate: "/certificates/certifications/Bootcamp-Operating_Systems-Excellence.pdf",
    // },
    // {
    //   degree: "Database Management System (DBMS)",
    //   description: "<p>Coding Ninjas<br />Certificate of Excellence</p>",
    //   timePeriod: "2024",
    //   certificate: "/certificates/certifications/Bootcamp-Database_Management_System_(DBMS)-Excellence.pdf",
    // },
    // {
    //   degree: "System Design",
    //   description: "<p>Coding Ninjas<br />Certificate of Excellence</p>",
    //   timePeriod: "2024",
    //   certificate: "/certificates/certifications/Bootcamp-System_Design-Excellence.pdf",
    // },
    {
        degree: "React | Full Stack Development",
        description: "<p>Coding Ninjas<br />Certificate of Excellence</p>",
        timePeriod: "2025",
        certificate: "/certificates/certifications/Bootcamp-React-Full_Stack_Development-Excellence.pdf",
    },
    // {
    //   degree: "Java Web Development (Spring Boot)",
    //   description: "<p>Coding Ninjas<br />Certificate of Excellence</p>",
    //   timePeriod: "2024",
    //   certificate: "/certificates/certifications/Bootcamp-Java_Web_Development-Spring_Boot-Excellence.pdf",
    // },
    {
      degree: "Data Structures & Algorithms with Java",
      description: "<p>Coding Ninjas<br />Certificate of Excellence</p>",
      timePeriod: "2024",
      certificate: "/certificates/certifications/Bootcamp-Data_Structure_&_Algorithm-Java-Excellence.pdf",
    },
    {
        degree: "Introduction to Java",
        description: "<p>Coding Ninjas<br />Certificate of Excellence</p>",
        timePeriod: "2024",
        certificate: "/certificates/certifications/Bootcamp-Introduction_To_Java-Excellence.pdf",
    },
    {
        degree: "Front End | Full Stack Development",
        description: "<p>Coding Ninjas<br />Certificate of Excellence</p>",
        timePeriod: "2024",
        certificate: "/certificates/certifications/Bootcamp-Front_End-Full_Stack_Development-Excellence.pdf",
    },
    {
        degree: "IoT (Internet of Things)",
        description: "<p>National Programme on Technology Enhanced Learning (NPTEL)<br />First Class with Distinction (98%)</p>",
        timePeriod: "2020",
        certificate: "/certificates/certifications/NPTEL_IoT.jpg",
    },
    {
        degree: "DOEACC 'A' Level",
        description: "<p>National Institute of Electronics & Information Technology (NIELIT)<br />First Class (6.8 CGPA)</p>",
        timePeriod: "2017-18",
        certificate: "",
    },
    {
        degree: "DOEACC 'O' Level",
        description: "<p>National Institute of Electronics & Information Technology (NIELIT)<br />First Class (6.8 CGPA)</p>",
        timePeriod: "2015-16",
        certificate: "/certificates/certifications/O_Level_DOEACC.pdf",
    },
];
export const honors = [
    {
        award: "Silver Medal in PG (MCA)",
        description: "<p>Galgotias University, Greater Noida<br />Second Highest CGPA Holder in complete batch of MCA (2019-22) as well as BCA+MCA (2017-22)<br/>First Class with Distinction (9.07 CGPA)</p>",
        timePeriod: "2019-22",
        certificate: "/certificates/honors/MCA_Silver_Medal.pdf",
    },
];
export const achievements = [
    // {
    //   achievement: "Abcd",
    //   description: "<p>National Programme on Technology Enhanced Learning (NPTEL)<br />First Class with Distinction (98%)</p>",
    //   timePeriod: "2023",
    //   certificate: "",
    // },
];
export const publication = [
    {
        publication: "Traffic Management using Cloud Computing",
        description: "<p>Jaipur National University<br />Published & Presented a Research Paper in 5th International Conference on Innovation Advancements in Engineering & Technology (IAET-2022) in association with All India Council for Technical Education</p>",
        timePeriod: "2022",
        certificate: "",
    },
];
export const workExperience = [
    {
        company_name: "Dataconsol Pvt. Ltd.",
        link: "https://dataconsol.com/",
        logo: "",
        location: "Telangana, Hyderabad (Remote)",
        work_type: "work_from_home",
        designation: "Full Stack Engineer",
        timePeriod: "May 2025 - Present",
        work_experience_description: "",
        work_experience_letter: "",
    },
    {
        company_name: "",
        // company_name: "Ammaiya Services Pvt. Ltd.",
        link: "https://ammaiya.com/",
        logo: "/images/ammaiya_logo.png",
        location: "Rohini, Delhi (Remote)",
        work_type: "work_from_home",
        designation: "Software Engineer (Freelance)",
        timePeriod: "Feb 2024 - May 2025",
        work_experience_description: "<p><ul><li>Streamlined <b>Functionalities</b> to the Web Applications by using <b>JavaScript, jQuery, AJAX,</b> increasing usefulness by 65%</li><li>Built <b>Email Templates</b> for Web Applications for providing Information to Customers, increasing interactivity by 30%</li><li><b>Enhanced user experience</b> by designing responsive UIs, boosting mobile traffic by 35%</li><li><b>Interpreted Client’s Requirement into Digital Solutions</b> and delivering the Effective & Efficient Results into the Project By Communicating with the Client Directly</li></ul></p>",
        work_experience_letter: "/experience_letter/Ammaiya_Service_Pvt_Ltd_Experince_Letter.pdf",
    },
    {
        company_name: "",
        // company_name: "SYMB Technologies Pvt. Ltd.",
        link: "https://www.symbtechnologies.com/",
        logo: "/images/symb_technologies_logo2.png",
        location: "Noida, Uttar Pradesh (Remote)",
        work_type: "work_from_home",
        designation: "Software Engineer",
        timePeriod: "Jan 2022 - Jan 2024",
        work_experience_description: "<p><ul><li>Developed and <b>maintained 7+ dynamic websites using React.js & Next.js,</b> increasing client engagement by 30%</li><li>Integrated <b>RESTful APIs</b> to enhance functionality, <b>reducing server response time by 40%</b></li><li>Integrated <b>Payment Gateways</b> like <b>Razorpay</b> to enhance functionality, <b>reducing server response time by 40%</b></li><li><b>Coached</b> interns and <b>Trained</b> them on live company projects.</li></ul></p>",
        work_experience_letter: "/experience_letter/SYMB_Technologies_Pvt_Ltd_Experience_Letter.pdf",
    },
];
export const companyProjects = [
    {
        company_name: "",
        // company_name: "SYMB Technologies Pvt Ltd.",
        company_description: "SYMB Technologies provide complete digital solutions to their clients in diverse sectors from Ecommerce, Solar & Banking to Manufacturing & Trading. SYMB Technologies helps agencies, startups, SMEs & large enterprises turn their ideas into reality by delivering solutions turn-key results on time and on budget.",
        link: "https://www.symbtechnologies.com/",
        logo: "/images/symb_technologies_logo2.png",
        darklogo: "/images/symb_technologies_logo4.png",
        location: "Noida, Uttar Pradesh",
        work_type: "work_from_home",
        company_projects: [
            {
                name: "FitCart Web Application (Customer Side)",
                link: "https://www.fitcart.com/",
                logo: "/images/fitcart-logo.png",
                timePeriod: "Jan 2022 - Nov 2022",
                description: "Implemented a full stack web application in which a customers can purchase products and subscribe to the services of company like personal diet plan, exercise schedules, queries, etc",
                highlightProject: true,
            },
            {
                name: "FitCart Web Application (Admin Side)",
                link: "https://admin.fitcart.com/",
                logo: "/images/fitcart-logo.png",
                timePeriod: "Jan 2022 - Nov 2022",
                description: "Implemented a full stack web application in which a company members can manage sales and purchase of products and manage their customers by providing them personal training services to the subscribed customers",
                highlightProject: true,
            },
            {
                name: "FidGuru Web Application (Customer Side)",
                link: "https://fidguru.in/",
                logo: "/images/fidguru-logo.png",
                timePeriod: "Nov 2022 - Feb 2023",
                description: "Implemented a full stack web application in which a users can find jobs by building their resume in both written as well as video format, can apply for jobs, and can schedule their interviews as well as can give real time online test to certify his/her skills to the interviewer",
                highlightProject: true,
            },
            {
                name: "FidGuru Web Application (Enterprise Side)",
                link: "https://enterprise.fidguru.in/",
                logo: "/images/fidguru-logo.png",
                timePeriod: "Nov 2022 - Feb 2023",
                description: "Implemented a full stack web application in which a users i.e. companies can post jobs,view candidates profile, take real time online exams to certify their skills, shortlist deserving candidates, schedule interviews with the candidates, view their resume in both written as well as video format and hire them for their own company",
                highlightProject: true,
            },
            {
                name: "FidGuru Web Application (Admin Side)",
                link: "https://admin.fidguru.in/",
                logo: "/images/fidguru-logo.png",
                timePeriod: "Nov 2022 - Feb 2023",
                description: "Implemented a full stack web application in which a company members can manage a job finding application for user services like managing posts for vacancies, creating question bank for particular topics, managing a test creating system to conduct real time test for users, managing user profiles and their video resumes, conducting online interviews and managing their different notifications for vacancies, interviews, etc",
                highlightProject: true,
            },
        ],
    },
];
export const personalProjects = [
    {
        name: "Busy Buy",
        link: "https://bejewelled-marshmallow-143603.netlify.app/",
        gitLink: "https://github.com/AdityaKapoor234/busy_buy_redux",
        logo: "",
        timePeriod: "May 2025",
        description: "Busy Buy is a web application with full-featured online marketplace with real-time inventory management, personalized shopping experiences, and seamless user management flow. Built with React (Front-End), Firebase (Back-End) & Redux + Redux-Persist (State Management), it's key features are like Product Management, User Authentication, Shopping Cart, Order History, Dark/Light Mode",
        highlightProject: true,
        type: "react",
    },
    {
        name: "Photofolios",
        link: "https://gorgeous-chaja-459a66.netlify.app/",
        gitLink: "https://github.com/AdityaKapoor234/photofolio_react",
        logo: "",
        timePeriod: "May 2025",
        description: "PhotoFolio is a web application for organizing, viewing, and managing photo albums with a sleek dark/light mode interface. Built with React (Front-End) and Firebase (Back-End), it's key features are like Theme System, Album Management, Image Handling. ",
        highlightProject: true,
        type: "react",
    },
    {
        name: "To Do List",
        link: "https://precious-malabi-60c504.netlify.app/",
        gitLink: "https://github.com/AdityaKapoor234/to-do-list-react",
        logo: "",
        timePeriod: "May 2025",
        description: "To-Do List is a web application where users can add various items to the to-do list and delete a particular item present inside the to-do list.",
        highlightProject: false,
        type: "react",
    },
    {
        name: "World Countries Details",
        link: "https://naughty-mcclintock-3f26b0.netlify.app/",
        gitLink: "https://gitlab.com/AdityaKapoor234/assignment-3-24-jan-2022-country-details",
        logo: "",
        timePeriod: "Jan 2022 - Feb 2022",
        description: "Implemented a Web Application in HTML5, CSS3, Java Script & AJAX with Rest API Integration in which user can see the information about all the countries in the world, search them by their names, open their maps, view their information like their population, currency, languages, neighbour countries, capital, time zone, etc",
        highlightProject: true,
        type: "html_css_javascript_api",
    },
    {
        name: "To Do List",
        link: "https://competent-bartik-e545d6.netlify.app/",
        gitLink: "https://gitlab.com/AdityaKapoor234/symb-assignment-2-to-do-list-21-jan-2022",
        logo: "",
        timePeriod: "Jan 2022 - Feb 2022",
        description: "Implemented a Web Application in HTML5, CSS3 & Java Script in which user can create a to do list, put the particular items into 3 different categories, delete a particular item separately or by selecting multiple items together or delete the complete list all at once",
        highlightProject: false,
        type: "html_css_javascript",
    },
    {
        name: "Photogram",
        link: "https://gilded-sundae-6c7d6e.netlify.app/",
        gitLink: "https://github.com/AdityaKapoor234/photogram",
        logo: "",
        timePeriod: "Jan 2024",
        description: "Implemented a Web Application in HTML5, CSS3 & Java Script in which user can view already existing post and create new posts also",
        highlightProject: true,
        type: "html_css_javascript",
    },
    {
        name: "Quiz Game",
        link: "https://coruscating-truffle-0aa211.netlify.app/",
        gitLink: "https://github.com/AdityaKapoor234/quiz_game",
        logo: "",
        timePeriod: "Jan 2024",
        description: "Implemented a Web Application in HTML5, CSS3 & Java Script in which user can play a quiz game and earn points (score)",
        highlightProject: false,
        type: "html_css_javascript",
    },
    {
        name: "Modifying Blog Page",
        link: "https://moonlit-quokka-7ca747.netlify.app/",
        gitLink: "https://github.com/AdityaKapoor234/blog_up_down_delete",
        logo: "",
        timePeriod: "Jan 2024",
        description: "Implemented a Web Application in HTML5, CSS3 & Java Script in which user can read existing blogs and move them up down or delete them",
        highlightProject: false,
        type: "html_css_javascript",
    },
    {
        name: "Seat Booking",
        link: "https://singular-custard-a0b206.netlify.app/",
        gitLink: "https://github.com/AdityaKapoor234/seat_booking_app",
        logo: "",
        timePeriod: "Jan 2024",
        description: "Implemented a Web Application in HTML5, CSS3 & Java Script in which user can select their seats for a particular movie to watch a particular film and also calculate the bill for their seats.",
        highlightProject: true,
        type: "html_css_javascript",
    },
    // {
    //   name: "Instrument Player",
    //   link: "",
    //   gitLink: "",
    //   logo: "",
    //   timePeriod: "Jan 2022 - Feb 2022",
    //   description: "",
    //   highlightProject: false,
    //   type: "html_css_javascript",
    // },
    {
        name: "Alarm Clock",
        link: "https://capable-banoffee-98cbca.netlify.app/",
        gitLink: "https://github.com/AdityaKapoor234/alarm-clock",
        logo: "",
        timePeriod: "Jan 2024",
        description: "Implemented a Web Application in HTML5, CSS3 & Java Script in which user can check time and set many alarms",
        highlightProject: false,
        type: "html_css_javascript",
    },
    {
        name: "Typing Speed Test",
        link: "https://curious-cactus-8c6e45.netlify.app/",
        gitLink: "https://github.com/AdityaKapoor234/speed_typing_test",
        logo: "",
        timePeriod: "Jan 2024",
        description: "Implemented a Web Application in HTML5, CSS3 & Java Script in which user can take a typing test and check his/her typing speed & accuracy",
        highlightProject: true,
        type: "html_css_javascript",
    },
    // {
    //   name: "Movie Recommendation",
    //   link: "",
    //   gitLink: "",
    //   logo: "",
    //   timePeriod: "Jan 2022 - Feb 2022",
    //   description: "",
    //   highlightProject: false,
    //   type: "html_css_javascript",
    // },
    // {
    //   name: "Pokemon Game",
    //   link: "",
    //   gitLink: "",
    //   logo: "",
    //   timePeriod: "Jan 2022 - Feb 2022",
    //   description: "",
    //   highlightProject: false,
    //   type: "html_css_javascript",
    // },
    // {
    //   name: "E-Commerce Website",
    //   link: "",
    //   gitLink: "",
    //   logo: "",
    //   timePeriod: "Jan 2022 - Feb 2022",
    //   description: "",
    //   highlightProject: false,
    //   type: "html_css_javascript",
    // },
    {
        name: "Music Player App",
        link: "https://melodious-halva-37904a.netlify.app/",
        gitLink: "https://github.com/AdityaKapoor234/music_player_capstone_project",
        logo: "",
        timePeriod: "Jan 2024",
        description: "Implemented a Web Application in HTML5, CSS3 & Java Script in which user can listen various songs, search those songs & playlists, and make their own playlist also to listen those songs in particular order mentioned by the user.",
        highlightProject: true,
        type: "html_css_javascript",
    },
    {
        name: "Music Player App (UI)",
        link: "https://gregarious-souffle-97f0e1.netlify.app/",
        gitLink: "https://github.com/AdityaKapoor234/music_player_ui_capstone_project",
        logo: "",
        timePeriod: "Jan 2024",
        description: "Implemented a Web Application in HTML5 & CSS3 in which user can view a UI for Music Player.",
        highlightProject: false,
        type: "html_css",
    },
    {
        name: "Stock Market Analysis",
        link: "https://eloquent-marzipan-f5a068.netlify.app/",
        gitLink: "https://github.com/AdityaKapoor234/stock_market_analysis_capstone_project",
        logo: "",
        timePeriod: "Feb 2024",
        description: "Implemented a Web Application in HTML5, CSS3, Java Script & AJAX with Rest API Integration in which user keep a watch on various different stocks & their performance over different time periods and know about the Company's Description, Profit & Book Value over Pictorial Representation (Chart).",
        highlightProject: true,
        type: "html_css_javascript_api",
    },
    {
        name: "Marvel Characters Project",
        link: "https://classy-unicorn-d52498.netlify.app/",
        gitLink: "https://github.com/AdityaKapoor234/marvel_characters_capstone_project",
        logo: "",
        timePeriod: "Feb 2024",
        description: "Implemented a Web Application in HTML5, CSS3, Java Script & AJAX with Rest API Integration in which user can view all the Characters mentioned in Marvel's API, Save their Own Favourite Characters & View their information like their Image, Description & Name of Comics, Events, Series and Stories in which they appeared.",
        highlightProject: true,
        type: "html_css_javascript_api",
    },
    {
        name: "JavaScript UI with SideBar Menu",
        link: "https://unruffled-mahavira-2548ae.netlify.app/",
        gitLink: "https://gitlab.com/-/ide/project/AdityaKapoor234/assignment-1-18-jan-2022/tree/main/-/Symb%20Assignment%201%2018%20Jan.html/",
        logo: "",
        timePeriod: "Jan 2022 - Feb 2022",
        description: "Implemented a Web Application UI in HTML5 & CSS3 which consist of a simple UI with a Contact Us Form & Side Bar Menu",
        highlightProject: false,
        type: "html_css",
    },
];
